export const API_URL = "http://localhost:5000/api";
export const CITIES = [
  "Indore",
  "Bhopal",
  "Jabalpur",
  "Gwalior",
  "Ujjain",
  "Sagar",
  "Ratlam",
  "Satna",
  "Murwara (Katni)",
  "Morena",
  "Singrauli",
  "Rewa",
  "Vidisha",
  "Ganjbasoda",
  "Shivpuri",
  "Mandsaur",
  "Neemuch",
  "Nagda",
  "Itarsi",
  "Sarni",
  "Sehore",
  "Mhow Cantonment",
  "Seoni",
  "Balaghat",
  "Ashok Nagar",
  "Tikamgarh",
  "Shahdol",
  "Pithampur",
  "Alirajpur",
  "Mandla",
  "Sheopur",
  "Shajapur",
  "Panna",
  "Raghogarh-Vijaypur",
  "Sendhwa",
  "Sidhi",
  "Pipariya",
  "Shujalpur",
  "Sironj",
  "Pandhurna",
  "Nowgong",
  "Mandideep",
  "Sihora",
  "Raisen",
  "Lahar",
  "Maihar",
  "Sanawad",
  "Sabalgarh",
  "Umaria",
  "Porsa",
  "Narsinghgarh",
  "Malaj Khand",
  "Sarangpur",
  "Mundi",
  "Nepanagar",
  "Pasan",
  "Mahidpur",
  "Seoni-Malwa",
  "Rehli",
  "Manawar",
  "Rahatgarh",
  "Panagar",
  "Wara Seoni",
  "Tarana",
  "Sausar",
  "Rajgarh",
  "Niwari",
  "Mauganj",
  "Manasa",
  "Nainpur",
  "Prithvipur",
  "Sohagpur",
  "Nowrozabad (Khodargama)",
  "Shamgarh",
  "Maharajpur",
  "Multai",
  "Pali",
  "Pachore",
  "Rau",
  "Mhowgaon",
  "Vijaypur",
  "Narsinghgarh",
];
export const STAR_RATING_FEEDBACK = {
  1: "Unsatisfactory",
  2: "Bad",
  3: "Average",
  4: "Satisfy",
  5: "Excellent",
};
